#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════════
# Tekton — New Client Setup Script
# Bootstraps a new client project from the Tekton template.
# Usage: ./scripts/setup-client.sh
# ═══════════════════════════════════════════════════════════════════════════════
set -euo pipefail

# ── Colors ──
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()  { echo -e "${CYAN}→${NC} $1"; }
ok()    { echo -e "${GREEN}✓${NC} $1"; }
err()   { echo -e "${RED}✗${NC} $1" >&2; }

# ── Prompt helpers ──
ask() {
  local prompt="$1" default="${2:-}"
  if [[ -n "$default" ]]; then
    read -rp "$(echo -e "${BOLD}$prompt${NC} [$default]: ")" value
    echo "${value:-$default}"
  else
    read -rp "$(echo -e "${BOLD}$prompt${NC}: ")" value
    echo "$value"
  fi
}

echo ""
echo -e "${BOLD}╔═══════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       Tekton — New Client Setup       ║${NC}"
echo -e "${BOLD}╚═══════════════════════════════════════╝${NC}"
echo ""

# ── Gather info ──
CLIENT_NAME=$(ask "Client name (e.g., Acme Corp)")
CLIENT_SLUG=$(echo "$CLIENT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')
DOMAIN=$(ask "Domain" "https://$CLIENT_SLUG.com")
SANITY_PROJECT_ID=$(ask "Sanity project ID")
SANITY_DATASET=$(ask "Sanity dataset" "production")

echo ""
info "Setting up ${BOLD}$CLIENT_NAME${NC} ($CLIENT_SLUG)"

# ── Update package.json name ──
if command -v node &> /dev/null; then
  node -e "
    const fs = require('fs');
    const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
    pkg.name = '$CLIENT_SLUG';
    fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
  "
  ok "Updated package.json name → $CLIENT_SLUG"
else
  err "Node.js not found — skipping package.json update"
fi

# ── Create .env.local from .env.example ──
if [[ -f .env.local ]]; then
  info ".env.local already exists — creating .env.local.new instead"
  ENV_FILE=".env.local.new"
else
  ENV_FILE=".env.local"
fi

REVALIDATE_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "generate-a-random-secret")

cat > "$ENV_FILE" << EOF
# ═══════════════════════════════════════════════════════════════════════════════
# $CLIENT_NAME — Environment Variables
# Generated by setup-client.sh on $(date +%Y-%m-%d)
# ═══════════════════════════════════════════════════════════════════════════════

# ─── Sanity CMS ──────────────────────────────────────────────────────────────
NEXT_PUBLIC_SANITY_PROJECT_ID=$SANITY_PROJECT_ID
NEXT_PUBLIC_SANITY_DATASET=$SANITY_DATASET
SANITY_API_READ_TOKEN=
SANITY_TOKEN=
SANITY_REVALIDATE_SECRET=$REVALIDATE_SECRET

# ─── Site ────────────────────────────────────────────────────────────────────
NEXT_PUBLIC_SITE_URL=$DOMAIN

# ─── Analytics (optional) ───────────────────────────────────────────────────
NEXT_PUBLIC_GA_MEASUREMENT_ID=

# ─── Error Tracking (optional) ──────────────────────────────────────────────
NEXT_PUBLIC_SENTRY_DSN=
SENTRY_AUTH_TOKEN=
SENTRY_ORG=
SENTRY_PROJECT=
EOF

ok "Created $ENV_FILE"

# ── Summary ──
echo ""
echo -e "${GREEN}${BOLD}Setup complete!${NC}"
echo ""
echo "  Next steps:"
echo "  1. Fill in Sanity API tokens in $ENV_FILE"
echo "     → sanity.io/manage → $SANITY_PROJECT_ID → API → Tokens"
echo "  2. Add CORS origin for $DOMAIN in Sanity"
echo "     → sanity.io/manage → $SANITY_PROJECT_ID → API → CORS origins"
echo "  3. Run: npm install && npm run dev"
echo "  4. Open Sanity Studio at /studio to create content"
echo ""
